[global]
   workgroup = GAP_RT
   realm = GAP-RT.RU
   security = ADS
   netbios name = samba-astra
   name resolve order = bcast host lmhosts wins

  #syslog = 1
   log file = /var/log/samba/log.%h
   log level = 2 auth_audit:3 smb:3
   logging = file syslog@1
   syslog = 1
  #syslog only = no
   max log size = 5000
   dns proxy = No
   winbind enum users = No
   winbind enum groups = No
   winbind use default domain = Yes
   winbind nss info = rfc2307
   winbind refresh tickets = yes
   winbind offline logon = yes

   client min protocol = SMB2
   server min protocol = SMB2


   idmap config * : backend = tdb
   idmap config * : range = 2000-9999
   idmap config GAP_RT : backend = rid
   idmap config GAP_RT : range = 10000-999999
   idmap config GAP_RT : rangesize = 200000

   kerberos method = system keytab

#[printers]
  # comment = All Printers
  # path = /var/tmp
  # printable = Yes
  # read only = Yes

#[print$]
  # comment = Printer Drivers
  # path = /var/lib/samba/printers
  # browseable = yes
  # read only = yes

[shared]
   path = /srv/samba/shared_folder
   read only = no
   valid users = @"Пользователи домена", "!citovmt", @"test-fs"
   invalid users = "@zapr1"
   read list = "@пользователи домена"
   write list = "@!citovmt", @"test-fs"
   inherit acls = Yes
   force group = "!citovmt"
   create mask = 0660
   directory mask = 0770

   vfs objects = full_audit recycle

#Логирование
   full_audit:prefix = %u|%I|%S
   full_audit:success = open close write pwrite unlinkat linkat
   full_audit:failure = renameat
   full_audit:facility = local5
   full_audit:priority = notice


[new1_share]
   path = /mnt/new1
   read only = no
   valid users = @"Пользователи домена", @"test-fs", "!citovmt"
   invalid users = @"zapr1"
   read list = @"Пользователи домена"
   write list = @"test-fs", "@!citovmt"
   inherit acls = Yes
   create mask = 0660
   directory mask = 0770

   vfs objects = full_audit recycle

#Логирование
   full_audit:prefix = %u|%I|%S
   full_audit:success = open close write pwrite unlinkat linkat
   full_audit:failure = renameat
   full_audit:facility = local5
   full_audit:priority = notice

#Корзина
   recycle:repository = .recycle
   recycle:keeptree = Yes
   recycle:versions = Yes
   recycle:touch = Yes
   recycle:minsize = 0
   recycle:maxsize = 0  # без ограничения по размеру
   recycle:exclude = *.tmp,*.temp,~$*
   recycle:excludedir = /.recycle,/tmp

[new2_share]
   path = /mnt/new2
   read only = yes
   valid users = "@пользователи домена", "!citovmt"
   invalid users = "@zapr1"
   read list = "@пользователи домена"
   write list = "@!citovmt"
   inherit acls = Yes
   force group = "!citovmt"
   create mask = 0660
   directory mask = 0770

   vfs objects = full_audit recycle

#Логирование
   full_audit:prefix = %u|%I|%S
   full_audit:success = open close write pwrite unlinkat linkat
   full_audit:failure = renameat
   full_audit:facility = local5
   full_audit:priority = notice

#Корзина
   recycle:repository = .recycle
   recycle:keeptree = Yes
   recycle:versions = Yes
   recycle:touch = Yes
   recycle:minsize = 0
   recycle:maxsize = 0  # без ограничения по размеру
   recycle:exclude = *.tmp,*.temp,~$*
   recycle:excludedir = /.recycle,/tmp
