[libdefaults]
default_realm = GAP-RT.RU
dns_lookup_realm = true
dns_lookup_kdc = true
ticket_lifetime = 24h
renew_lifetime = 7d
forwardable = true
rdns = false

[realms]
GAP-RT.RU = {
kdc = dc03.gap-rt.ru
admin_server = dc03.gap-rt.ru
default_domain = gap-rt.ru
}

[domain_realm]
.gap-rt.ru = GAP-RT.RU
gap-rt.ru = GAP-RT.RU
