http_port 3128
cache_mem 1024 MB
max_filedesc 16384
forwarded_for off
request_header_access X-Forwarded-For deny all
request_header_access Via deny all
request_header_access Cache-Control deny all
request_header_access From deny all
cache_store_log none
coredump_dir /var/spool/squid
ftp_user anonymous@

acl localnet src 10.0.0.0/8
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16
acl localhost src 127.0.0.1/32
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 21
acl Safe_ports port 443
acl Safe_ports port 70
acl Safe_ports port 210
acl Safe_ports port 1025-65535
acl Safe_ports port 280
acl Safe_ports port 488
acl Safe_ports port 591
acl Safe_ports port 777
acl CONNECT method CONNECT

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow localhost
http_access deny manager

acl IP_Users src 192.168.0.0/16
http_access allow IP_Users

# Блокировки
acl WoT_domain dstdomain .worldoftanks.net .worldoftanks-sea.com .worldoftanks.eu .worldoftanks.cn .worldoftanks.com .worldoftanks.ru
http_access deny WoT_domain
acl Viruses01 dstdomain .bestwayshop.ru.com
http_access deny Viruses01
acl WhatsAppBlock dstdomain .whatsapp.com
http_access deny WhatsAppBlock
acl ban_domains dstdomain techmestore.pw otrasoper.ga
http_access deny ban_domains

http_access allow localnet
http_access deny all

# Подключение ufdbGuard
url_rewrite_program /usr/local/ufdbguard/bin/ufdbguardd
url_rewrite_children 20
dns_v4_first on

refresh_pattern ^ftp: 1440 20% 10080
refresh_pattern ^gopher: 1440 0% 1440
refresh_pattern -i (/cgi-bin/|\?) 0 0% 0
refresh_pattern . 0 20% 4320
