dbhome /var/lib/ufdbguard/db
logdir /var/log/ufdbguard
pidfile /run/ufdbguard/ufdbguardd.pid
tempdir /tmp

category chat { domainlist chat/domains }
category media { domainlist media/domains }
category porn { domainlist porn/domains }
category proxy { domainlist proxy/domains }
category adv { domainlist adv/domains }
category mail { domainlist mail/domains }
category updates { domainlist updates/domains }
category white { domainlist white/domains }
category white_autodesk { domainlist white_autodesk/domains }
category cloud { domainlist cloud/domains }

acl {
   full_direct_ip {
      src 192.168.1.23 192.168.3.161 192.168.3.169 192.168.3.230 192.168.1.195 192.168.2.131 192.168.3.133 192.168.3.123 192.168.3.139 192.168.3.137 192.168.3.231 192.168.5.66 192.168.5.187
      pass white all
   }
   default {
      pass white !mail !adv !chat !media !porn !proxy !updates !cloud
      redirect http://srv10.gap-rt.ru/redir/en/access_denied.html
   }
}
